spin_locked_gcd: Move paging allocator init outside GcdMemLock
Intel physical platforms currently fail during the `Vec::with_capacity()`
call in `PagingAllocator::new()`:

```
  INFO - Initializing paging for the GCD
  ERROR - panicked at C:\src\uefi-dxe-core\dxe_core\src\tpl_lock.rs:76:43:
  Re-entrant locks for "GcdMemLock" not permitted.
```

The lock is reacquired on entry to `allocate_memory_space()`.

This sets up the vector outside the second GCD lock so the vector
is already set up with capacity for the `page_pool` vector before
initializing the GCD.

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>